### ISSUE TITLE
Error While Compiling

### ISSUE THREAD

**Issue by vasundharab** [baskren/Forms9PatchDemo#1] opened 2016-02-27 13:34 UTC
Hi,
When i am compiling this project getting this error even though all references and packages are properly installed. Kindly help me out to use this for Frame background image.
Error MT2002: Failed to resolve "System.Reflection.Emit.OpCode" reference from "mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" (MT2002) (Forms9PatchDemo.iOS)

**Comment by baskren** [comment] 2016-02-27 22:08
@vasundharab,  

1. Can you send me a small project that replicates the issue? 
2. Are you running this on Mac, PC w/ Xamarin Studio, Visual Studio 2012, Visual Studio 2013, or Visual Studio 2015?
3. What Nuget package version of Forms9Patch are you using?


- Ben

**Comment by baskren** [comment] 2016-02-27 23:21
@vasundharab, my apologies for not noticing earlier that you are trying to use the demo project.  I've just downloaded a fresh copy of it and ran it on Mac Xamarin Studio w/o a problem.  I'll try on on PC here in a moment as well.

**Comment by vasundharab** [comment] 2016-02-28 08:32
Hi Baskren,

I am also doing it with Mac Xamarin studio but getting that error.
These are my tool chain versions

Xamarin Studio
Version 5.10.2 (build 56)

Xamarin.iOS
Version: 9.4.1.25 (Enterprise Edition)

Apple Developer Tools
Xcode 7.2.1 (9548.1)
Build 7C1002

Operating System
Mac OS X 10.11.2

Let me know if you need any other details .

**Comment by baskren** [comment] 2016-02-28 13:55
@vasundharab , perhaps the fastest way to get to the root cause would be to do a screen share via something like good hangouts or Skype.  I'm going to be at my computer for the next couple of hours.  You can contact me via Google Hangout at ben@buildcalc.com and Skype at buildcalc.

**Comment by baskren** [comment] 2016-02-28 13:59
I forgot to ask - could you send me a stack trace?

By the way, our systems are almost identical (the differences being you're on the Enterprise version of Xamarin while I'm on the Business and you're using OSX 10.11.2 while I'm on 10.11.3).

**Comment by baskren** [comment] 2016-02-28 18:44
FYI: Source of issue was a setting on the obfuscator.  Has been fixed in release 0.9.9.1.

**Closed by baskren** 2016-02-28 18:44 UTC
